# Generated by Django 4.0.6 on 2022-07-05 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.IntegerField()),
                ('num', models.IntegerField(blank=True, null=True)),
                ('num2', models.IntegerField(blank=True, null=True)),
                ('timea', models.CharField(choices=[('Arte Elétrica', 'Arte Elétrica'), ('Dinos', 'Dinos'), ('Empório Rebelo', 'Empório Rebelo'), ('EuroBlack', 'EuroBlack'), ('Flamengo', 'Flamengo'), ('Juventude', 'Juventude'), ('Kosminho', 'Kosminho'), ('Levis', 'Levis'), ('Os Pior', 'Os Pior'), ('Paulista', 'Paulista'), ('Salgueiro', 'Salgueiro'), ('São Lucas', 'São Lucas'), ('Vimec', 'Vimec'), ('VKT', 'VKT')], max_length=30)),
                ('placara', models.IntegerField(blank=True, null=True)),
                ('placarb', models.IntegerField(blank=True, null=True)),
                ('timeb', models.CharField(choices=[('Arte Elétrica', 'Arte Elétrica'), ('Dinos', 'Dinos'), ('Empório Rebelo', 'Empório Rebelo'), ('EuroBlack', 'EuroBlack'), ('Flamengo', 'Flamengo'), ('Juventude', 'Juventude'), ('Kosminho', 'Kosminho'), ('Levis', 'Levis'), ('Os Pior', 'Os Pior'), ('Paulista', 'Paulista'), ('Salgueiro', 'Salgueiro'), ('São Lucas', 'São Lucas'), ('Vimec', 'Vimec'), ('VKT', 'VKT')], max_length=30)),
                ('gols_total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('rodada',),
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('nome_abr', models.CharField(max_length=5, verbose_name='Apelido')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='fotos_time', verbose_name='foto')),
                ('cores', models.CharField(blank=True, max_length=30, verbose_name='Cores')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Pontuar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j', models.IntegerField(default=0)),
                ('pg', models.IntegerField(default=0)),
                ('v', models.IntegerField(default=0)),
                ('e', models.IntegerField(default=0)),
                ('d', models.IntegerField(default=0)),
                ('gp', models.IntegerField(default=0)),
                ('gc', models.IntegerField(default=0)),
                ('sg', models.IntegerField(default=0)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suico.time')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Tabelas',
            },
        ),
    ]
