# Generated by Django 3.0.7 on 2022-07-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='timea',
            field=models.CharField(choices=[('Art Elétrica', 'Art Elétrica'), ('Dinos', 'Dinos'), ('Empório Rebelo', 'Empório Rebelo'), ('EuroBlack', 'EuroBlack'), ('Flamengo', 'Flamengo'), ('Juventude', 'Juventude'), ('Kosminho', 'Kosminho'), ('Levis', 'Levis'), ('Os Pior', 'Os Pior'), ('Paulista', 'Paulista'), ('Salgueiro', 'Salgueiro'), ('São Lucas', 'São Lucas'), ('Vimec', 'Vimec'), ('VKT', 'VKT')], max_length=30),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='timeb',
            field=models.CharField(choices=[('Art Elétrica', 'Art Elétrica'), ('Dinos', 'Dinos'), ('Empório Rebelo', 'Empório Rebelo'), ('EuroBlack', 'EuroBlack'), ('Flamengo', 'Flamengo'), ('Juventude', 'Juventude'), ('Kosminho', 'Kosminho'), ('Levis', 'Levis'), ('Os Pior', 'Os Pior'), ('Paulista', 'Paulista'), ('Salgueiro', 'Salgueiro'), ('São Lucas', 'São Lucas'), ('Vimec', 'Vimec'), ('VKT', 'VKT')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pontuar',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='time',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
